

export const categorieOrCost = {
    "El Español - En grupo - Turma": "Curso Espanhol",
    "El Español - X1": "Curso Espanhol",
    "El Español - X2": "Curso Espanhol",
    "El Español - X3": "Curso Espanhol",
    "Fluency Way Class - Adults": "Curso Adults and YA",
    "Fluency Way Class - Kids": "Curso Kids",
    "Fluency Way Class - Little Ones": "Curso Kids",
    "Fluency Way Class - Online": "Curso Adults and YA",
    "Fluency Way Class - Standard One": "Curso Adults and YA",
    "Fluency Way Class - Teens": "Curso Teens",
    "Fluency Way X - 4X": "Curso Particular",
    "Fluency Way X - Double X": "Curso Particular",
    "Fluency Way X - One X": "Curso Particular",
    "Fluency Way X Plus - 4X": "Curso Particular",
    "Fluency Way X Plus - Double X": "Curso Particular",
    "Fluency Way X Plus - One X": "Curso Particular",
    "Fluency Way X Plus - Triple X": "Curso Particular",
    "Fluency Way X - Triple X": "Curso Particular",
    "Tecnologia - Office Essential": "Curso Informática",
}

export const financial_account = {
    "Boleto": 'Conta PJ Conta Azul',
    "Cartão de crédito via link": 'Conta PJ Conta Azul',
    "Cartão de débito via outros bancos": 'Rede',
    "Cartão de crédito via outro bancos": 'Rede',
    "Dinheiro": 'Caixa Físico',
    "Outros": 'Bolsas, isenções e outros meios indeterminados',
    "Pix": 'Inter_PJ',
    "Transferência bancária": 'Inter_PJ',
    "Pix cobrança": 'Conta PJ Conta Azul',
    "Sem pagamento": 'Bolsas, isenções e outros meios indeterminados',

    "": 'Amais Financeira',
    "": 'Azulzinha da Caixa',
    "": 'Bolsistas Integrais',
    "": 'BTG Pactual - PJ',
    "": 'Caixa Econômica Conta PJ',
    "": 'Caixa Excedente',
    "": 'Cartão Caixa',
    "": 'Cartão Inter PJ',
    "": 'Cartão PJ Santander 21',
    "": 'Cartão PJ Santander 26',
    "": 'Cartão Santander PJ 12',
    "": 'Itaú_PJ',
    "": 'Receba Fácil',
    "": 'Santander_PJ',
    "": 'ZOOP'

}

export const paymentType = {
    "Boleto": "BOLETO_BANCARIO",
    "Cartão de crédito via link": "CARTAO_CREDITO_VIA_LINK",
    "Boleto bancário": "BOLETO_BANCARIO",
    "Cartão de crédito via outro bancos": "CARTAO_CREDITO",
    "Cartão de débito via outros bancos": "CARTAO_DEBITO",
    "Dinheiro": "DINHEIRO",
    "PIX - Pagamento Instantâneo": "PIX_PAGAMENTO_INSTANTANEO",
    "Pix": "PIX_PAGAMENTO_INSTANTANEO",
    "Pix cobrança": "PIX_COBRANCA",
    "Sem pagamento": "SEM_PAGAMENTO",
    "Isenção": "SEM_PAGAMENTO",
    "Transferência bancária": "TRANSFERENCIA_BANCARIA",
    "Outros": "OUTRO",

    "": "DEBITO_AUTOMATICO",
    "": "PROGRAMA_FIDELIDADE",
    "": "CARTEIRA_DIGITAL",
    "": "CASHBACK",
    "": "CHEQUE",
    "": "CREDITO_LOJA",
    "": "CREDITO_VIRTUAL",
    "": "BANKING_DEPOSIT",
    "": "VALE_ALIMENTACAO",
    "": "VALE_COMBUSTIVEL",
    "": "VALE_PRESENTE",
    "": "VALE_REFEICAO",
}